---
  #inclide_vars

- name: "Vars {{ ansible_distribution }}"
  include_vars: "vars-{{ ansible_distribution }}.yml"
  when: ansible_distribution == "Ubuntu"

#include_tasks

- name: "Install {{ ansible_distribution }}"
  include_tasks: "tasks-{{ ansible_distribution }}.yml"
  when: ansible_distribution == "Ubuntu"
